version: 2
jobs:
  check:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: poetry install
      - run: poetry run pylint keras_nalu
      - run: poetry run pylint tests
      - run: poetry run py.test --cov-fail-under=100 -sk 'test_load_and_predict or test_pretrained or test_train_static_addition'
workflows:
  version: 2
  check:
    jobs:
      - check
